@startuml

cloud {
    interface "Counter Server" as counter
}

node "Servlet Container" {
    package "Application" {
        [core.jar] --> [web-counter-api.jar]
        [web-counter-api.jar] ..> counter : use
    }
}

@enduml